# Generated by Django 3.1.7 on 2021-03-21 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Albums',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, unique=True)),
                ('reference', models.IntegerField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, upload_to='albums/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Bb',
        ),
        migrations.AddField(
            model_name='albums',
            name='artist',
            field=models.ManyToManyField(blank=True, related_name='albums', to='start.Artist'),
        ),
    ]
