# Generated by Django 3.1.7 on 2021-03-22 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('start', '0005_booking_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='albums',
            old_name='artist',
            new_name='artists',
        ),
    ]
